name: ShellCheck

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'ushunit'
      - 'tests/**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Clone ushunit repo
        uses: actions/checkout@v4
        with:
          path: ushunit

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      