name: Unit testing

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'ushunit'
      - 'tests/**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Unit testing
    runs-on: ubuntu-latest

    steps:
      - name: Clone ushunit repo
        uses: actions/checkout@v4
        with:
          path: ushunit

      - name: Test asserts
        working-directory: ushunit
        run: |
          ./ushunit tests/asserts.sh

      - name: Test isolation
        working-directory: ushunit
        run: |
          ./ushunit -i tests/asserts.sh tests/isolation.sh
